### ISSUE TITLE
always return false (android 9+)

### ISSUE THREAD

**Issue by atmanegara** [diegorribeiro/cordova-plugin-mock-location-checker#6]
in android 9 or above , return mock is always false but for coordinates not following mock (fake gps) but according to current location and this is true, the problem is mock info is false , is there any solution?

**Comment by arkawingsure** [comment]
Yes same issue i am also facing can anyone help me ???

**Comment by diegorribeiro** [comment]
Hello, this repo will not receive future updates.
Have you tried using this other one?
https://github.com/smarques84/MockLocationDetector

**Comment by arkakarmakar85** [comment]
But I am using Ionic, can you send me a capacitor or capacitor-based plugin?
